# Generated by Django 3.1.3 on 2020-11-26 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_mybookslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybookslist',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookslist', to='catalog.book'),
        ),
        migrations.AlterField(
            model_name='mybookslist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userslist', to=settings.AUTH_USER_MODEL),
        ),
    ]
