# Generated by Django 3.1.3 on 2020-11-30 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_auto_20201130_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
    ]
