# Generated by Django 3.1.3 on 2020-12-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201201_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
